apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  # Instance family and size requirements
  instanceStorePolicy: "NVME"
  
  # Root volume
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 20Gi
        volumeType: gp3
        deleteOnTermination: true
  
  # Node metadata options
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  
  # Subnet discovery using tags
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "${cluster_name}"
  
  # Security group discovery using tags  
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "${cluster_name}"
  
  # User data script
  userData: |
    #!/bin/bash
    /etc/eks/bootstrap.sh ${cluster_name}
  
  # Tags for instances
  tags:
    Name: "karpenter-${cluster_name}"
    Environment: "development"
    ManagedBy: "karpenter"
